name: CI

on:
  push:
    branches: [ branch3 ]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps: 

    - uses: actions/checkout@v2

    - name: List all original files
      run: ls
      
    - name: Install pyhton
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run python script
      run: python create_file.py

    - name: List all new files
      run: ls
    

    

    
