name: CI

on:
  push:
    branches: [ branch4 ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps: 

    - uses: actions/checkout@v2

    - name: List all original files
      run: ls
      
    - name: Install pyhton
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run python script
      run: python create_file1.py

    - name: List all new files
      run: ls

  display:
    runs-on: ubuntu-22.04
    needs: build
    if: always()

    steps:
      - name: Print text
        run: echo hallo from another job
    

    

    
