name: CI

on:
  push:
    branches: [ branch3 ]

jobs:
  my_job:
    name: Checking Custom Env Variables
    runs-on: ubuntu-22.04

    env: 
      platform: Azure
      region: Central
      profile_path: profile/


    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Display custom environment variables
        run: |
          echo "The platform is ${{ env.plateform }}"
          echo "The region is ${{ env.region }}"
          if [ "${{ env.plateform }}" = "Azure" ]; then
            echo "The platform is Azure. Proceeding with further steps."
          else
            echo "The platform is not Azure."
          fi