name: outputs-demo2
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map step outputs to job outputs
    outputs:
      output1: ${{ steps.step1.outputs.data }}

    steps:
    
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install pyhton
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
    
      - name: Run python script
        id: contents
        run: 
          python create_txt_file.py
          contents=$( cat readme.txt )
          echo "data=$contents" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Output1: ${{ needs.job1.outputs.output1 }}"
