name: outputs-demo
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}
      
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
        env:
          test: hello

      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
        env:
          test: world

      - id: step3
        run: |
          var="test12345678"
          echo "test=$var" >> "$GITHUB_OUTPUT"
        env:
          test: test12345678
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}
