name: outputs-demo
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map step outputs to job outputs
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}

    steps:
      - id: step1
        run: |
          echo "test=hello" >> $GITHUB_OUTPUT
          echo "Setting output1 to hello"
      - id: step2
        run: |
          echo "test=world" >> $GITHUB_OUTPUT
          echo "Setting output2 to world"
      - id: step3
        run: |
          echo "test=hi" >> $GITHUB_OUTPUT
          var=hi
          echo "Setting output3 to $var"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Output1: ${{ needs.job1.outputs.output1 }}"
          echo "Output2: ${{ needs.job1.outputs.output2 }}"
          echo "Output3: ${{ needs.job1.outputs.output3 }}"
