name: outputs-demo2
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      output1: ${{ steps.step1.outputs.data }}

    steps:
    
      - name: Install python
        continue-on-error: true
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
    
      - name: Run python script
        id: contents
        run: |
          pwd
          ls -la
          python create_txt_file.py
          ls -la
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'StanleyClassyan'
          git config --global user.email 'stanleyapclassyan@gmail.com'
          git add readme.txt
          git commit -m "Add readme.txt"
          git push

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Output1: ${{ needs.job1.outputs.output1 }}"
